In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("50_Startups.csv")

In [3]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [6]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [7]:
df.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [8]:
df['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [9]:
df['State'].value_counts()

New York      17
California    17
Florida       16
Name: State, dtype: int64

In [12]:
a=pd.get_dummies(df['State'],drop_first=True)

In [13]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [14]:
a.head()

Florida  New York
0        0         1
1        0         0
2        1         0
3        0         1
4        1         0

In [16]:
df=df.drop(['State'] , axis=1)

In [17]:
df.head()

R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

In [19]:
df=pd.concat([df,a] , axis=1)

In [20]:
df.head()

R&D Spend  Administration  Marketing Spend     Profit  Florida  New York
0  165349.20       136897.80        471784.10  192261.83        0         1
1  162597.70       151377.59        443898.53  191792.06        0         0
2  153441.51       101145.55        407934.54  191050.39        1         0
3  144372.41       118671.85        383199.62  182901.99        0         1
4  142107.34        91391.77        366168.42  166187.94        1         0

In [21]:
x=df.drop(['Profit'],axis=1)
y=df['Profit']

In [22]:
x.head()

R&D Spend  Administration  Marketing Spend  Florida  New York
0  165349.20       136897.80        471784.10        0         1
1  162597.70       151377.59        443898.53        0         0
2  153441.51       101145.55        407934.54        1         0
3  144372.41       118671.85        383199.62        0         1
4  142107.34        91391.77        366168.42        1         0

In [23]:
y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=11)

In [27]:
x_train

R&D Spend  Administration  Marketing Spend  Florida  New York
39   38558.51        82982.09        174999.30        0         0
49       0.00       116983.80         45173.06        0         0
21   78389.47       153773.43        299737.29        0         1
15  114523.61       122616.84        261776.23        0         1
0   165349.20       136897.80        471784.10        0         1
23   67532.53       105751.03        304768.73        1         0
41   27892.92        84710.77        164470.71        1         0
11  100671.96        91790.61        249744.55        0         0
6   134615.46       147198.87        127716.82        0         0
3   144372.41       118671.85        383199.62        0         1
31   61136.38       152701.92         88218.23        0         1
29   65605.48       153032.06        107138.38        0         1
40   28754.33       118546.05        172795.67        0         0
47       0.00       135426.92             0.00        0         0
46    1315.46       115816.21        297114.46        1         0
20   76253.86       113867.30        298664.47        0         0
10  101913.08       110594.11        229160.95        1         0
1   162597.70       151377.59        443898.53        0         0
44   22177.74       154806.14         28334.72        0         0
34   46426.07       157693.92        210797.67        0         0
4   142107.34        91391.77        366168.42        1         0
32   63408.86       129219.61         46085.25        0         0
28   66051.52       182645.56        118148.20        1         0
24   77044.01        99281.34        140574.81        0         1
18   91749.16       114175.79        294919.57        1         0
7   130298.13       145530.06        323876.68        1         0
33   55493.95       103057.49        214634.81        1         0
12   93863.75       127320.38        249839.44        1         0
13   91992.39       135495.07        252664.93        0         0
17   94657.16       145077.58        282574.31        0         1
27   72107.60       127864.55        353183.81        0         1
16   78013.11       121597.55        264346.06        0         0
25   64664.71       139553.16        137962.62        0         0

In [29]:
y_train

39     81005.76
49     14681.40
21    111313.02
15    129917.04
0     192261.83
23    108733.99
41     77798.83
11    144259.40
6     156122.51
3     182901.99
31     97483.56
29    101004.64
40     78239.91
47     42559.73
46     49490.75
20    118474.03
10    146121.95
1     191792.06
44     65200.33
34     96712.80
4     166187.94
32     97427.84
28    103282.38
24    108552.04
18    124266.90
7     155752.60
33     96778.92
12    141585.52
13    134307.35
17    125370.37
27    105008.31
16    126992.93
25    107404.34
Name: Profit, dtype: float64

In [30]:
len(x_train) , len (y_train)

(33, 33)

In [31]:
len (x_test) , len (y_test)

(17, 17)

In [33]:
from sklearn.linear_model import LinearRegression

In [35]:
reg=LinearRegression()

In [38]:
reg.fit(x_train,y_train)

LinearRegression()

In [40]:
reg.coef_

array([ 8.64329624e-01,  7.12539493e-03,  3.06409736e-02, -5.50485207e+02,
       -6.33665237e+03])

In [41]:
reg.intercept_

41591.69166575266

In [39]:
from sklearn.metrics import r2_score

In [42]:
y_train_pred=reg.predict(x_train)

In [43]:
y_train_pred[:5]

array([ 80872.38320029,  43809.39397757, 113289.31921754, 143135.96001129,
       193602.62617354])

In [44]:
r2_score(y_train,y_train_pred)*100

96.24396264097771

In [45]:
y_test_pred=reg.predict(x_test)

In [46]:
y_test_pred[:5]

array([ 86085.24084971,  37062.54542705,  72884.19060685, 115165.76968517,
       186885.46253478])

In [48]:
training_part=pd.DataFrame({'actual point': y_train , 'prediction point ': y_train_pred})

In [49]:
training_part

actual point  prediction point 
39      81005.76       80872.383200
49      14681.40       43809.393978
21     111313.02      113289.319218
15     129917.04      143135.960011
0      192261.83      193602.626174
23     108733.99      109503.501166
41      77798.83       70793.023879
11     144259.40      136911.909493
6      156122.51      162906.039370
3      182901.99      172627.583361
31      97483.56       91888.177570
29     101004.64       96333.037286
40      78239.91       72584.225879
47      42559.73       42556.661954
46      49490.75       52107.310052
20     118474.03      117462.881412
10     146121.95      136937.441889
1      191792.06      196809.808791
44      65200.33       62731.827631
34      96712.80       89301.796579
4      166187.94      175739.749528
32      97427.84       98730.685464
28     103282.38      103053.089519
24     108552.04      106861.227279
18     124266.90      130192.893758
7      155752.60      164622.596100
33      96778.92       96317.216246
12     141585.52      130732.957861
13     134307.35      129810.794843
17     125370.37      126762.113816
27     105008.31      109312.755287
16     126992.93      117986.984894
25     107404.34      102704.996512

In [47]:
r2_score(y_test,y_test_pred)*100

88.29561428747645

In [50]:
reg.score(x_train,y_train)*100

96.24396264097771

In [52]:
reg.score(x_test,y_test)*100

88.29561428747645