In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df=pd.read_csv('titanic.csv')

In [10]:
df

PassengerId                                               Name  Pclass  \
0              1                            Braund, Mr. Owen Harris       3   
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2              3                             Heikkinen, Miss. Laina       3   
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4              5                           Allen, Mr. William Henry       3   
..           ...                                                ...     ...   
886          887                              Montvila, Rev. Juozas       2   
887          888                       Graham, Miss. Margaret Edith       1   
888          889           Johnston, Miss. Catherine Helen "Carrie"       3   
889          890                              Behr, Mr. Karl Howell       1   
890          891                                Dooley, Mr. Patrick       3   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1    female  38.0      1      0          PC 17599  71.2833   C85        C   
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3    female  35.0      1      0            113803  53.1000  C123        S   
4      male  35.0      0      0            373450   8.0500   NaN        S   
..      ...   ...    ...    ...               ...      ...   ...      ...   
886    male  27.0      0      0            211536  13.0000   NaN        S   
887  female  19.0      0      0            112053  30.0000   B42        S   
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S   
889    male  26.0      0      0            111369  30.0000  C148        C   
890    male  32.0      0      0            370376   7.7500   NaN        Q   

     Survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
886         0  
887         1  
888         0  
889         1  
890         0  

[891 rows x 12 columns]

In [11]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)

In [12]:
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [14]:
a=pd.get_dummies(df.Sex,drop_first=True)

In [15]:
a

male
0       1
1       0
2       0
3       0
4       1
..    ...
886     1
887     0
888     0
889     1
890     1

[891 rows x 1 columns]

In [16]:
df=df.drop(['Sex'],axis=1)

In [17]:
df.head()

Pclass   Age     Fare  Survived
0       3  22.0   7.2500         0
1       1  38.0  71.2833         1
2       3  26.0   7.9250         1
3       1  35.0  53.1000         1
4       3  35.0   8.0500         0

In [19]:
df.isnull().sum()

Pclass        0
Age         177
Fare          0
Survived      0
dtype: int64

In [20]:
b = df.Age.mean()

In [21]:
b

29.69911764705882

In [22]:
df.Age.fillna(b,inplace=True)

In [23]:
df.head()

Pclass   Age     Fare  Survived
0       3  22.0   7.2500         0
1       1  38.0  71.2833         1
2       3  26.0   7.9250         1
3       1  35.0  53.1000         1
4       3  35.0   8.0500         0

In [24]:
df.Age.isnull().sum()

0

In [25]:
df.head()

Pclass   Age     Fare  Survived
0       3  22.0   7.2500         0
1       1  38.0  71.2833         1
2       3  26.0   7.9250         1
3       1  35.0  53.1000         1
4       3  35.0   8.0500         0

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Age       891 non-null    float64
 2   Fare      891 non-null    float64
 3   Survived  891 non-null    int64  
dtypes: float64(2), int64(2)
memory usage: 28.0 KB


In [27]:
x=df.drop(['Survived'],axis=1)
y=df['Survived']

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
x_train,x_test,y_train,y_test = train_test_split (x,y,test_size=0.3)

In [30]:
x_train

Pclass        Age      Fare
614       3  35.000000    8.0500
882       3  22.000000   10.5167
778       3  29.699118    7.7375
805       3  31.000000    7.7750
681       1  27.000000   76.7292
..      ...        ...       ...
737       1  35.000000  512.3292
223       3  29.699118    7.8958
702       3  18.000000   14.4542
96        1  71.000000   34.6542
467       1  56.000000   26.5500

[623 rows x 3 columns]

In [31]:
y_train

614    0
882    0
778    0
805    0
681    1
      ..
737    1
223    0
702    0
96     0
467    0
Name: Survived, Length: 623, dtype: int64

In [32]:
x_test

Pclass        Age      Fare
27        1  19.000000  263.0000
309       1  30.000000   56.9292
428       3  29.699118    7.7500
262       1  52.000000   79.6500
719       3  33.000000    7.7750
..      ...        ...       ...
539       1  22.000000   49.5000
366       1  60.000000   75.2500
386       3   1.000000   46.9000
625       1  61.000000   32.3208
643       3  29.699118   56.4958

[268 rows x 3 columns]

In [33]:
y_test

27     0
309    1
428    0
262    0
719    0
      ..
539    1
366    1
386    0
625    0
643    1
Name: Survived, Length: 268, dtype: int64

In [34]:
len(x_train),len(y_train)

(623, 623)

In [35]:
len(x_test),len(y_test)

(268, 268)

In [37]:
from sklearn.naive_bayes import GaussianNB

In [38]:
reg = GaussianNB()

In [39]:
reg.fit(x_train,y_train)

GaussianNB()

In [40]:
y_train_pred=reg.predict(x_train)

In [41]:
y_train_pred[:5]

array([0, 0, 0, 0, 1], dtype=int64)

In [42]:
y_test_pred = reg.predict(x_test)

In [43]:
y_test_pred[:5]

array([1, 1, 0, 1, 0], dtype=int64)

In [49]:
## For Trainning Data

In [50]:
from sklearn.metrics import confusion_matrix

In [51]:
confusion_matrix(y_train,y_train_pred)

array([[323,  54],
       [143, 103]], dtype=int64)

In [52]:
from sklearn.metrics import accuracy_score

In [53]:
accuracy_score(y_train,y_train_pred)*100

68.37881219903691

In [56]:
from sklearn.metrics import classification_report

In [57]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       0.69      0.86      0.77       377
           1       0.66      0.42      0.51       246

    accuracy                           0.68       623
   macro avg       0.67      0.64      0.64       623
weighted avg       0.68      0.68      0.67       623



In [54]:
## For Test Data

In [55]:
confusion_matrix(y_test,y_test_pred)

array([[141,  31],
       [ 63,  33]], dtype=int64)

In [62]:
y_test_pred = reg.predict(x_test)

In [63]:
y_test_pred[:5]

array([1, 1, 0, 1, 0], dtype=int64)

In [65]:
accuracy_score(y_test,y_test_pred)*100

64.92537313432835

In [66]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.69      0.82      0.75       172
           1       0.52      0.34      0.41        96

    accuracy                           0.65       268
   macro avg       0.60      0.58      0.58       268
weighted avg       0.63      0.65      0.63       268

