In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('titanic.csv')

In [6]:
df

PassengerId                                               Name  Pclass  \
0              1                            Braund, Mr. Owen Harris       3   
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2              3                             Heikkinen, Miss. Laina       3   
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4              5                           Allen, Mr. William Henry       3   
..           ...                                                ...     ...   
886          887                              Montvila, Rev. Juozas       2   
887          888                       Graham, Miss. Margaret Edith       1   
888          889           Johnston, Miss. Catherine Helen "Carrie"       3   
889          890                              Behr, Mr. Karl Howell       1   
890          891                                Dooley, Mr. Patrick       3   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1    female  38.0      1      0          PC 17599  71.2833   C85        C   
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3    female  35.0      1      0            113803  53.1000  C123        S   
4      male  35.0      0      0            373450   8.0500   NaN        S   
..      ...   ...    ...    ...               ...      ...   ...      ...   
886    male  27.0      0      0            211536  13.0000   NaN        S   
887  female  19.0      0      0            112053  30.0000   B42        S   
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S   
889    male  26.0      0      0            111369  30.0000  C148        C   
890    male  32.0      0      0            370376   7.7500   NaN        Q   

     Survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
886         0  
887         1  
888         0  
889         1  
890         0  

[891 rows x 12 columns]

In [3]:
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Name         891 non-null    object 
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    object 
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Ticket       891 non-null    object 
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object 
 10  Embarked     889 non-null    object 
 11  Survived     891 non-null    int64  
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [5]:
df.isnull().sum()

PassengerId      0
Name             0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Survived         0
dtype: int64

In [7]:
median = df.Age.median()

In [8]:
median

28.0

In [9]:
df.Age.fillna(median,inplace=True)

In [10]:
df

PassengerId                                               Name  Pclass  \
0              1                            Braund, Mr. Owen Harris       3   
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2              3                             Heikkinen, Miss. Laina       3   
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4              5                           Allen, Mr. William Henry       3   
..           ...                                                ...     ...   
886          887                              Montvila, Rev. Juozas       2   
887          888                       Graham, Miss. Margaret Edith       1   
888          889           Johnston, Miss. Catherine Helen "Carrie"       3   
889          890                              Behr, Mr. Karl Howell       1   
890          891                                Dooley, Mr. Patrick       3   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1    female  38.0      1      0          PC 17599  71.2833   C85        C   
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3    female  35.0      1      0            113803  53.1000  C123        S   
4      male  35.0      0      0            373450   8.0500   NaN        S   
..      ...   ...    ...    ...               ...      ...   ...      ...   
886    male  27.0      0      0            211536  13.0000   NaN        S   
887  female  19.0      0      0            112053  30.0000   B42        S   
888  female  28.0      1      2        W./C. 6607  23.4500   NaN        S   
889    male  26.0      0      0            111369  30.0000  C148        C   
890    male  32.0      0      0            370376   7.7500   NaN        Q   

     Survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
886         0  
887         1  
888         0  
889         1  
890         0  

[891 rows x 12 columns]

In [11]:
df.isnull().sum()

PassengerId      0
Name             0
Pclass           0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Survived         0
dtype: int64

In [12]:
df.Cabin.isnull().sum()

687

In [13]:
df.Cabin.fillna('Missing',inplace=True)

In [14]:
df['Cabin_replace']=df.Cabin.astype(str).str[0]

In [15]:
df.Cabin_replace.head()

0    M
1    C
2    M
3    C
4    M
Name: Cabin_replace, dtype: object

In [16]:
df.Embarked.fillna(df.Embarked.mode()[0],inplace=True)

In [17]:
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare    Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500  Missing        S   
1  female  38.0      1      0          PC 17599  71.2833      C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250  Missing        S   
3  female  35.0      1      0            113803  53.1000     C123        S   
4    male  35.0      0      0            373450   8.0500  Missing        S   

   Survived Cabin_replace  
0         0             M  
1         1             C  
2         1             M  
3         1             C  
4         0             M

In [18]:
df=df.drop(["Cabin"],axis=1)

In [19]:
df

PassengerId                                               Name  Pclass  \
0              1                            Braund, Mr. Owen Harris       3   
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2              3                             Heikkinen, Miss. Laina       3   
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4              5                           Allen, Mr. William Henry       3   
..           ...                                                ...     ...   
886          887                              Montvila, Rev. Juozas       2   
887          888                       Graham, Miss. Margaret Edith       1   
888          889           Johnston, Miss. Catherine Helen "Carrie"       3   
889          890                              Behr, Mr. Karl Howell       1   
890          891                                Dooley, Mr. Patrick       3   

        Sex   Age  SibSp  Parch            Ticket     Fare Embarked  Survived  \
0      male  22.0      1      0         A/5 21171   7.2500        S         0   
1    female  38.0      1      0          PC 17599  71.2833        C         1   
2    female  26.0      0      0  STON/O2. 3101282   7.9250        S         1   
3    female  35.0      1      0            113803  53.1000        S         1   
4      male  35.0      0      0            373450   8.0500        S         0   
..      ...   ...    ...    ...               ...      ...      ...       ...   
886    male  27.0      0      0            211536  13.0000        S         0   
887  female  19.0      0      0            112053  30.0000        S         1   
888  female  28.0      1      2        W./C. 6607  23.4500        S         0   
889    male  26.0      0      0            111369  30.0000        C         1   
890    male  32.0      0      0            370376   7.7500        Q         0   

    Cabin_replace  
0               M  
1               C  
2               M  
3               C  
4               M  
..            ...  
886             M  
887             B  
888             M  
889             C  
890             M  

[891 rows x 12 columns]

In [20]:
df.isnull().sum()

PassengerId      0
Name             0
Pclass           0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         0
Survived         0
Cabin_replace    0
dtype: int64

In [21]:
a=pd.get_dummies(df['Sex'],drop_first=True)

In [22]:
a

male
0       1
1       0
2       0
3       0
4       1
..    ...
886     1
887     0
888     0
889     1
890     1

[891 rows x 1 columns]

In [24]:
b=pd.get_dummies(df['Embarked'],drop_first=True)

In [25]:
b

Q  S
0    0  1
1    0  0
2    0  1
3    0  1
4    0  1
..  .. ..
886  0  1
887  0  1
888  0  1
889  0  0
890  1  0

[891 rows x 2 columns]

In [26]:
c=pd.get_dummies(df['Cabin_replace'],drop_first=True)

In [27]:
c

B  C  D  E  F  G  M  T
0    0  0  0  0  0  0  1  0
1    0  1  0  0  0  0  0  0
2    0  0  0  0  0  0  1  0
3    0  1  0  0  0  0  0  0
4    0  0  0  0  0  0  1  0
..  .. .. .. .. .. .. .. ..
886  0  0  0  0  0  0  1  0
887  1  0  0  0  0  0  0  0
888  0  0  0  0  0  0  1  0
889  0  1  0  0  0  0  0  0
890  0  0  0  0  0  0  1  0

[891 rows x 8 columns]

In [29]:
df=pd.concat([df,a,b,c],axis=1)

In [30]:
df

PassengerId                                               Name  Pclass  \
0              1                            Braund, Mr. Owen Harris       3   
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2              3                             Heikkinen, Miss. Laina       3   
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4              5                           Allen, Mr. William Henry       3   
..           ...                                                ...     ...   
886          887                              Montvila, Rev. Juozas       2   
887          888                       Graham, Miss. Margaret Edith       1   
888          889           Johnston, Miss. Catherine Helen "Carrie"       3   
889          890                              Behr, Mr. Karl Howell       1   
890          891                                Dooley, Mr. Patrick       3   

        Sex   Age  SibSp  Parch            Ticket     Fare Embarked  ...  Q  \
0      male  22.0      1      0         A/5 21171   7.2500        S  ...  0   
1    female  38.0      1      0          PC 17599  71.2833        C  ...  0   
2    female  26.0      0      0  STON/O2. 3101282   7.9250        S  ...  0   
3    female  35.0      1      0            113803  53.1000        S  ...  0   
4      male  35.0      0      0            373450   8.0500        S  ...  0   
..      ...   ...    ...    ...               ...      ...      ...  ... ..   
886    male  27.0      0      0            211536  13.0000        S  ...  0   
887  female  19.0      0      0            112053  30.0000        S  ...  0   
888  female  28.0      1      2        W./C. 6607  23.4500        S  ...  0   
889    male  26.0      0      0            111369  30.0000        C  ...  0   
890    male  32.0      0      0            370376   7.7500        Q  ...  1   

     S  B  C  D  E  F  G  M  T  
0    1  0  0  0  0  0  0  1  0  
1    0  0  1  0  0  0  0  0  0  
2    1  0  0  0  0  0  0  1  0  
3    1  0  1  0  0  0  0  0  0  
4    1  0  0  0  0  0  0  1  0  
..  .. .. .. .. .. .. .. .. ..  
886  1  0  0  0  0  0  0  1  0  
887  1  1  0  0  0  0  0  0  0  
888  1  0  0  0  0  0  0  1  0  
889  0  0  1  0  0  0  0  0  0  
890  0  0  0  0  0  0  0  1  0  

[891 rows x 23 columns]

In [31]:
df=df.drop(['PassengerId','Name','Sex','Ticket','Cabin_replace','Embarked'],axis=True)

In [32]:
df

Pclass   Age  SibSp  Parch     Fare  Survived  male  Q  S  B  C  D  E  F  \
0         3  22.0      1      0   7.2500         0     1  0  1  0  0  0  0  0   
1         1  38.0      1      0  71.2833         1     0  0  0  0  1  0  0  0   
2         3  26.0      0      0   7.9250         1     0  0  1  0  0  0  0  0   
3         1  35.0      1      0  53.1000         1     0  0  1  0  1  0  0  0   
4         3  35.0      0      0   8.0500         0     1  0  1  0  0  0  0  0   
..      ...   ...    ...    ...      ...       ...   ... .. .. .. .. .. .. ..   
886       2  27.0      0      0  13.0000         0     1  0  1  0  0  0  0  0   
887       1  19.0      0      0  30.0000         1     0  0  1  1  0  0  0  0   
888       3  28.0      1      2  23.4500         0     0  0  1  0  0  0  0  0   
889       1  26.0      0      0  30.0000         1     1  0  0  0  1  0  0  0   
890       3  32.0      0      0   7.7500         0     1  1  0  0  0  0  0  0   

     G  M  T  
0    0  1  0  
1    0  0  0  
2    0  1  0  
3    0  0  0  
4    0  1  0  
..  .. .. ..  
886  0  1  0  
887  0  0  0  
888  0  1  0  
889  0  0  0  
890  0  1  0  

[891 rows x 17 columns]

In [33]:
x=df.drop(['Survived'],axis=1)
y=df['Survived']

In [34]:
x.head()

Pclass   Age  SibSp  Parch     Fare  male  Q  S  B  C  D  E  F  G  M  T
0       3  22.0      1      0   7.2500     1  0  1  0  0  0  0  0  0  1  0
1       1  38.0      1      0  71.2833     0  0  0  0  1  0  0  0  0  0  0
2       3  26.0      0      0   7.9250     0  0  1  0  0  0  0  0  0  1  0
3       1  35.0      1      0  53.1000     0  0  1  0  1  0  0  0  0  0  0
4       3  35.0      0      0   8.0500     1  0  1  0  0  0  0  0  0  1  0

In [35]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [36]:
from sklearn.model_selection import train_test_split?

Object `train_test_split` not found.


In [40]:
from sklearn.model_selection import train_test_split

In [41]:
x_train,x_test,y_train,y_test = train_test_split (x,y,test_size=0.33,random_state=42)

In [43]:
x_train

Pclass   Age  SibSp  Parch      Fare  male  Q  S  B  C  D  E  F  G  M  T
6         1  54.0      0      0   51.8625     1  0  1  0  0  0  1  0  0  0  0
718       3  28.0      0      0   15.5000     1  1  0  0  0  0  0  0  0  1  0
685       2  25.0      1      2   41.5792     1  0  0  0  0  0  0  0  0  1  0
73        3  26.0      1      0   14.4542     1  0  0  0  0  0  0  0  0  1  0
882       3  22.0      0      0   10.5167     0  0  1  0  0  0  0  0  0  1  0
..      ...   ...    ...    ...       ...   ... .. .. .. .. .. .. .. .. .. ..
106       3  21.0      0      0    7.6500     0  0  1  0  0  0  0  0  0  1  0
270       1  28.0      0      0   31.0000     1  0  1  0  0  0  0  0  0  1  0
860       3  41.0      2      0   14.1083     1  0  1  0  0  0  0  0  0  1  0
435       1  14.0      1      2  120.0000     0  0  1  1  0  0  0  0  0  0  0
102       1  21.0      0      1   77.2875     1  0  1  0  0  1  0  0  0  0  0

[596 rows x 16 columns]

In [44]:
y_train

6      0
718    0
685    0
73     0
882    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 596, dtype: int64

In [45]:
from sklearn.tree import DecisionTreeClassifier

In [46]:
reg = DecisionTreeClassifier()

In [47]:
reg.fit(x_train,y_train)

DecisionTreeClassifier()

In [48]:
y_train_pred=reg.predict(x_train)

In [50]:
y_train_pred[:10]

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [51]:
y_train

6      0
718    0
685    0
73     0
882    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 596, dtype: int64

In [52]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [53]:
confusion_matrix(y_train,y_train_pred)

array([[373,   1],
       [ 10, 212]], dtype=int64)

In [54]:
accuracy_score(y_train,y_train_pred)*100

98.15436241610739

In [55]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.99       374
           1       1.00      0.95      0.97       222

    accuracy                           0.98       596
   macro avg       0.98      0.98      0.98       596
weighted avg       0.98      0.98      0.98       596



In [56]:
## For TesT Data 

In [57]:
y_test_pred=reg.predict(x_test)

In [58]:
y_test_pred[:10]

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [59]:
confusion_matrix(y_test,y_test_pred)

array([[140,  35],
       [ 35,  85]], dtype=int64)

In [60]:
accuracy_score(y_test,y_test_pred)*100

76.27118644067797

In [61]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.80      0.80      0.80       175
           1       0.71      0.71      0.71       120

    accuracy                           0.76       295
   macro avg       0.75      0.75      0.75       295
weighted avg       0.76      0.76      0.76       295

