In [1]:
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('bill_authentication.csv')

In [4]:
df.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [5]:
df.isnull().sum()

Variance    0
Skewness    0
Curtosis    0
Entropy     0
Class       0
dtype: int64

In [6]:
df.Class.unique()

array([0, 1], dtype=int64)

In [7]:
df.Class.value_counts()

0    762
1    610
Name: Class, dtype: int64

In [8]:
x=df.drop(['Class'],axis=1)
y=df['Class']

In [9]:
x.head()

Variance  Skewness  Curtosis  Entropy
0   3.62160    8.6661   -2.8073 -0.44699
1   4.54590    8.1674   -2.4586 -1.46210
2   3.86600   -2.6383    1.9242  0.10645
3   3.45660    9.5228   -4.0112 -3.59440
4   0.32924   -4.4552    4.5718 -0.98880

In [10]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test = train_test_split (x,y, test_size = 0.33 , random_state= 42)

In [14]:
x_train.head()

Variance  Skewness  Curtosis  Entropy
1201  -0.87340 -0.033118  -0.20165  0.55774
1094   2.01770  1.798200  -2.95810  0.20990
224   -0.36038  4.115800   3.11430 -0.37199
939   -2.05290  3.838500  -0.79544 -1.21380
274    5.27560  0.138630   0.12138  1.14350

In [15]:
y_train.head()

1201    1
1094    1
224     0
939     1
274     0
Name: Class, dtype: int64

In [16]:
x_test.head()

Variance  Skewness  Curtosis  Entropy
430  1.569100    6.3465   -0.1828  -2.4099
588 -0.278020    8.1881   -3.1338  -2.5276
296  0.051979    7.0521   -2.0541  -3.1508
184 -1.755900   11.9459    3.0946  -4.8978
244  2.428700    9.3821   -3.2477  -1.4543

In [17]:
y_test.head()

430    0
588    0
296    0
184    0
244    0
Name: Class, dtype: int64

In [19]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
reg = DecisionTreeClassifier()

In [21]:
reg.fit(x_train,y_train)

DecisionTreeClassifier()

In [22]:
y_train_pred = reg.predict(x_train)

In [23]:
y_train[:10]

1201    1
1094    1
224     0
939     1
274     0
323     0
1098    1
409     0
325     0
847     1
Name: Class, dtype: int64

In [24]:
y_train_pred[:10]

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 1], dtype=int64)

In [26]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [27]:
confusion_matrix(y_train,y_train_pred)

array([[505,   0],
       [  0, 414]], dtype=int64)

In [28]:
accuracy_score(y_train,y_train_pred)*100

100.0

In [29]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       505
           1       1.00      1.00      1.00       414

    accuracy                           1.00       919
   macro avg       1.00      1.00      1.00       919
weighted avg       1.00      1.00      1.00       919



In [30]:
# Finding For Test Data 

In [31]:
y_test_pred =reg.predict(x_test)

In [32]:
confusion_matrix(y_test,y_test_pred)

array([[255,   2],
       [  6, 190]], dtype=int64)

In [33]:
accuracy_score(y_test,y_test_pred)*100

98.23399558498896

In [34]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       257
           1       0.99      0.97      0.98       196

    accuracy                           0.98       453
   macro avg       0.98      0.98      0.98       453
weighted avg       0.98      0.98      0.98       453



# Random Forest

In [37]:
from sklearn.ensemble import RandomForestClassifier

In [38]:
reg = RandomForestClassifier()

In [39]:
reg.fit(x_train,y_train)

RandomForestClassifier()

In [40]:
y_train_pred = reg.predict(x_train)

In [41]:
y_train_pred[:10]

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 1], dtype=int64)

In [43]:
confusion_matrix(y_train,y_train_pred)

array([[505,   0],
       [  0, 414]], dtype=int64)

In [44]:
accuracy_score(y_train,y_train_pred)*100

100.0

In [47]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       505
           1       1.00      1.00      1.00       414

    accuracy                           1.00       919
   macro avg       1.00      1.00      1.00       919
weighted avg       1.00      1.00      1.00       919



In [45]:
y_test_pred = reg.predict(x_test)

In [46]:
y_test_pred[:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [48]:
confusion_matrix(y_test,y_test_pred)

array([[257,   0],
       [  3, 193]], dtype=int64)

In [49]:
accuracy_score(y_test,y_test_pred)*100

99.33774834437085

In [50]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       257
           1       1.00      0.98      0.99       196

    accuracy                           0.99       453
   macro avg       0.99      0.99      0.99       453
weighted avg       0.99      0.99      0.99       453

