In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('Iris.csv')

In [3]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [4]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [6]:
df.Species.value_counts()

Iris-versicolor    50
Iris-virginica     50
Iris-setosa        50
Name: Species, dtype: int64

In [7]:
df['Species_label'], _ = pd.factorize(df['Species'])
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [8]:
df.Species_label.head()

0    0
1    0
2    0
3    0
4    0
Name: Species_label, dtype: int64

In [9]:
x=df.drop(['Species_label', 'Species'],axis=1)
y=df['Species_label']

In [10]:
x.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

In [11]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Species_label, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)

In [14]:
x_train.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
96    97            5.7           2.9            4.2           1.3
105  106            7.6           3.0            6.6           2.1
66    67            5.6           3.0            4.5           1.5
0      1            5.1           3.5            1.4           0.2
122  123            7.7           2.8            6.7           2.0

In [15]:
y_train.head()

96     1
105    2
66     1
0      0
122    2
Name: Species_label, dtype: int64

In [16]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
reg=DecisionTreeClassifier()

In [21]:
reg.fit(x_train,y_train)

DecisionTreeClassifier()

In [22]:
y_train_pred=reg.predict(x_train)

In [24]:
y_train_pred[:10]

array([1, 2, 1, 0, 2, 1, 0, 0, 0, 1], dtype=int64)

In [26]:
y_test_pred=reg.predict(x_test)

In [27]:
y_test_pred[:10]

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1], dtype=int64)

In [28]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [29]:
confusion_matrix(y_train,y_train_pred)

array([[31,  0,  0],
       [ 0, 35,  0],
       [ 0,  0, 34]], dtype=int64)

In [31]:
accuracy_score(y_train,y_train_pred)*100

100.0

In [39]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        31
           1       1.00      1.00      1.00        35
           2       1.00      1.00      1.00        34

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100



In [32]:
# For Test Data

In [33]:
y_test_pred=reg.predict(x_test)

In [34]:
y_test_pred[:10]

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1], dtype=int64)

In [35]:
confusion_matrix(y_test,y_test_pred)

array([[19,  0,  0],
       [ 0, 15,  0],
       [ 0,  0, 16]], dtype=int64)

In [37]:
accuracy_score(y_test,y_test_pred)*100

100.0

In [38]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        16

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50

