In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('heart.csv')

In [3]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [8]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
fbs         0
restecg     0
exang       0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [11]:
df=df.drop(['trestbps'],axis=1)

In [12]:
df

age  sex  cp  fbs  restecg  exang  slope  ca  thal  target
0     63    1   3    1        0      0      0   0     1       1
1     37    1   2    0        1      0      0   0     2       1
2     41    0   1    0        0      0      2   0     2       1
3     56    1   1    0        1      0      2   0     2       1
4     57    0   0    0        1      1      2   0     2       1
..   ...  ...  ..  ...      ...    ...    ...  ..   ...     ...
298   57    0   0    0        1      1      1   0     3       0
299   45    1   3    0        1      0      1   0     3       0
300   68    1   0    1        1      0      1   2     3       0
301   57    1   0    0        1      1      1   1     3       0
302   57    0   1    0        0      0      1   1     2       0

[303 rows x 10 columns]

In [14]:
x=df.drop(['target'],axis=1)
y=df['target']

In [15]:
x.head()

age  sex  cp  fbs  restecg  exang  slope  ca  thal
0   63    1   3    1        0      0      0   0     1
1   37    1   2    0        1      0      0   0     2
2   41    0   1    0        0      0      2   0     2
3   56    1   1    0        1      0      2   0     2
4   57    0   0    0        1      1      2   0     2

In [16]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split

In [80]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=22)

In [81]:
x_train

age  sex  cp  fbs  restecg  exang  slope  ca  thal
279   61    1   0    0        0      1      1   1     2
171   48    1   1    0        1      0      0   0     3
55    52    1   1    0        1      0      2   1     2
268   54    1   0    0        0      1      1   2     2
170   56    1   2    1        0      1      1   1     1
..   ...  ...  ..  ...      ...    ...    ...  ..   ...
14    58    0   3    1        0      0      2   0     2
146   44    0   2    0        1      0      1   1     2
84    42    0   0    0        0      0      1   0     2
300   68    1   0    1        1      0      1   2     3
132   42    1   1    0        1      0      2   0     2

[203 rows x 9 columns]

In [82]:
y_train

279    0
171    0
55     1
268    0
170    0
      ..
14     1
146    1
84     1
300    0
132    1
Name: target, Length: 203, dtype: int64

In [83]:
k=np.arange(1,25)
k

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [84]:
for i , j in enumerate(k):
    print(i, j)

0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 10
10 11
11 12
12 13
13 14
14 15
15 16
16 17
17 18
18 19
19 20
20 21
21 22
22 23
23 24


In [85]:
c=np.empty(len(k))
c

array([0.72, 0.69, 0.69, 0.71, 0.79, 0.78, 0.75, 0.74, 0.77, 0.77, 0.76,
       0.75, 0.75, 0.72, 0.73, 0.74, 0.74, 0.76, 0.74, 0.74, 0.73, 0.72,
       0.69, 0.73])

In [86]:
from sklearn.neighbors import KNeighborsClassifier

In [87]:
train_accuracy = np.empty(len(k))
test_accuracy = np.empty(len(k))

for i , j in enumerate(k):
    knn = KNeighborsClassifier(n_neighbors = j)  # j = 1 , 2 , 3
    knn.fit(x_train , y_train)
    train_accuracy[i] = knn.score(x_train,y_train)
    test_accuracy[i] = knn.score(x_test,y_test)
    print(train_accuracy[i] , test_accuracy[i])

1.0 0.69
0.9211822660098522 0.64
0.9113300492610837 0.69
0.8669950738916257 0.69
0.8571428571428571 0.73
0.8423645320197044 0.71
0.8275862068965517 0.69
0.8325123152709359 0.69
0.8177339901477833 0.7
0.8177339901477833 0.74
0.7980295566502463 0.74
0.8029556650246306 0.72
0.7980295566502463 0.67
0.7881773399014779 0.69
0.8078817733990148 0.69
0.7980295566502463 0.7
0.8029556650246306 0.7
0.7783251231527094 0.69
0.7881773399014779 0.67
0.7733990147783252 0.66
0.7733990147783252 0.67
0.7733990147783252 0.65
0.7783251231527094 0.66
0.7586206896551724 0.63


In [88]:
a = np.where(test_accuracy == max(test_accuracy))
a

(array([ 9, 10], dtype=int64),)

In [89]:
k[a]

array([10, 11])

In [90]:
knn=KNeighborsClassifier(n_neighbors=11)
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=11)

## Confusion matrix

In [92]:
from sklearn.metrics import confusion_matrix

In [93]:
y_train_pred=knn.predict(x_train)

In [94]:
y_train_pred[:5]

array([0, 1, 1, 0, 1], dtype=int64)

In [95]:
y_test_pred=knn.predict(x_test)

In [96]:
y_test_pred

array([1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [98]:
confusion_matrix(y_train,y_train_pred)

array([[ 60,  29],
       [ 12, 102]], dtype=int64)

In [97]:
from sklearn.metrics import accuracy_score,classification_report

#### For Training Data

In [99]:
accuracy_score(y_train,y_train_pred)*100

79.80295566502463

## Classification Report For Test Data

In [101]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       0.83      0.67      0.75        89
           1       0.78      0.89      0.83       114

    accuracy                           0.80       203
   macro avg       0.81      0.78      0.79       203
weighted avg       0.80      0.80      0.79       203



In [102]:
confusion_matrix(y_test,y_test_pred)

array([[30, 19],
       [ 7, 44]], dtype=int64)

#### For Test Data

In [112]:
accuracy_score(y_train,y_train_pred)*100

79.80295566502463

## Classification Report For Test Data

In [104]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.81      0.61      0.70        49
           1       0.70      0.86      0.77        51

    accuracy                           0.74       100
   macro avg       0.75      0.74      0.73       100
weighted avg       0.75      0.74      0.74       100

